### ISSUE TITLE
Update project timeline to address Verdant RITE project issues.

### ISSUE THREAD

**Issue by Neil-Swanson** [mhk-env/mhk-env.github.io#11]
# Update project timeline to address Verdant RITE project issues.
**Issue emailed to team by Zach Barr and Sharon Kramer on 01/07/2021.**

![image](https://user-images.githubusercontent.com/45704311/104515032-12e79b80-55a7-11eb-8b1b-daf47ef8a84a.png)

**Neil Swanson responded for clarification:**

![image](https://user-images.githubusercontent.com/45704311/104515116-33aff100-55a7-11eb-91a7-0a4465102afe.png)

**Sharon and Zach responded:**

![image](https://user-images.githubusercontent.com/45704311/104515160-45919400-55a7-11eb-8436-fbf7a1d6154d.png)

**Comment by bbest** [comment]
Pasting text from images in thread above...

----
From: Sharon Kramer <skramer@harveyecology.com>
Date: Fri, Jan 8, 2021 at 9:55 AM
Subject: RE: MHK Toolkit Project Timeline RITE Project Update

My interpretation – they do not have a final license approved yet but FERC let them move ahead with deployment, which they did in late 2020, on a temporary (month to month?) basis (I note, I could not find anything from FERC stating month to month but just rather approval with conditions).  Rather than month to month, can we asterisk and then footnote as temporary approval or something like that?Interestingly, I could not find anything from FERC that has a start date 1/1/21, just this attachment.  So I am confused too.Not sure how helpful this is, I don’t like to question Verdant but trying to make their table jive with the FERC elibrary is not straightforward. 

----
From: Zach Barr [mailto:zbarr@kearnswest.com] 
Sent: Friday, January 8, 2021 6:57 AM
Subject: RE: MHK Toolkit Project Timeline RITE Project Update 

+Sharon for her to weigh-in/confirm. Yes, they will only apply to the RITE project (it may be easiest to use a different symbol rather than another triangle to show this on the timeline). I don’t know if Month to Month was a typo but I think if we want to describe it as Month to Month it should be put on the pin map when you click on their project you can see it described as such. Sharon, does that capture more or less what you were thinking? 

----
From: Neil Swanson <nswanson@integral-corp.com>
Sent: Thursday, January 7, 2021 4:15 PM
Subject: RE: MHK Toolkit Project Timeline RITE Project Update

Hi Zach, Before I make changes to the MHK project timeline, I want to make sure I understand this correctly.  I’ve included a screenshot of the current timeline figure for quick reference.  Sharon is requesting that we add four new symbol colors/legend items, which at this point will only apply to the RITE project – “Pilot License Issued”, “Draft Re-License App”, “Final Re-license App”, and “Re-license Issued”, correct?  Also, do you know what is meant by “Re-license issuedMonth to Month 1/1/21”?  I’m guessing the symbol should be set to 1/1/21 and the “Month to Month” was a typo? 

----
From: Zach Barr <zbarr@kearnswest.com>
Sent: Thursday, January 7, 2021 3:52 PM
Subject: MHK Toolkit Project Timeline RITE Project Update

Hi all, Please see below in Sharon’s latest email some changes we’d like to make to the Verdant RITE project timeline in the MHK Toolkit. Let me know if you have any questions. 

----
From: Sharon Kramer <skramer@harveyecology.com>
Sent: Monday, January 4, 2021 10:36 AM
Subject: RE: water quality question

Zach I think maybe adding or changing these points
- Add: Pilot license issued 1/23/2012
- Change Draft and Final license application to Draft Re-License Application and Final Re-license Application
- Add: Re-license issued Month to Month 1/1/21 

----
From: Zach Barr [mailto:zbarr@kearnswest.com]
Sent: Monday, January 4, 2021 9:23 AM
Subject: RE: water quality question

Right – and it may be confusing if other developers rely on that timeline if it is not the typical order things happen. Are there any updates we should make based on what he provided? I want to be as responsive as possible without having to redo or update everything if it isn’t warranted.

----
From: Sharon Kramer <skramer@harveyecology.com>
Sent: Monday, January 4, 2021 8:41 AM
Subject: RE: water quality question

No questions but its just too detailed.  For example, its odd to me that they submitted their DLA without the EA, which came a year later.  I think that level of detail is too much.

----
From: Zach Barr [mailto:zbarr@kearnswest.com]
Sent: Monday, January 4, 2021 7:00 AM
Subject: RE: water quality question

Hi Sharon, I hope the surgery went well and you’re recovering in good spirits! Please find attached updates recommended by Verdant on the RITE Timeline. Is there any questions you have related to this? Thanks!Zach

----
From: Sharon Kramer <skramer@harveyecology.com>
Sent: Tuesday, December 15, 2020 12:58 PM
Subject: RE: water quality question

Thanks! Jonathan Colby was messaging me with questions about our source for the project timeline. I think there are dates for the RITE project that he thinks are incorrect. Do you know where we pulled those from? I thought we got them from Verdant… 

----
From: Sharon Kramer <skramer@harveyecology.com>
Sent: Tuesday, December 15, 2020 12:44 PM
Subject: water quality question

Zach – BOEMs lease and FERCs license, and Corps permits, cannot violate regulations affecting water quality, so yes, clean water act is the statute for water quality, and all of the other permitting processes have to address it.  Sharon H. Kramer, Ph.D.

**Comment by bbest** [comment]
![newplot](https://user-images.githubusercontent.com/2837257/104519607-8f31ad00-55ae-11eb-98eb-2a3f6f1b7832.png)

So how to change symbology etc to incorporate this?
